/** preload 白名单通道，渲染进程只能使用这些通道与主进程通信 */
export const IPC_CHANNELS = {
  ConfigGet: 'config:get',
  ConfigCopyPassword: 'config:copyPassword',
  ConfigCopyText: 'config:copyText',
  ConfigOpenRecordDir: 'config:openRecordDir',
  ConfigOpenLogDir: 'config:openLogDir',
  ConfigOpenEnvFile: 'config:openEnvFile',
  ConfigOpenWeb: 'config:openWeb',
  AppRestart: 'app:restart',
  AppGetVersion: 'app:getVersion',
  FtpTestConnection: 'ftp:testConnection',
  FtpListDir: 'ftp:listDir',
  FtpDelete: 'ftp:delete',
  FtpDownload: 'ftp:download',
  FtpUploadFiles: 'ftp:uploadFiles',
  FtpSyncDeployRuntime: 'ftp:syncDeployRuntime',
  FtpClearRoot: 'ftp:clearRoot',
  FtpCleanIncoming: 'ftp:cleanIncoming',
  PluginList: 'plugin:list',
  PluginCreate: 'plugin:create',
  PluginSaveMapping: 'plugin:saveMapping',
  PluginPush: 'plugin:push',
  PluginDelete: 'plugin:delete',
  PluginOpenRoot: 'plugin:openRoot',
  PluginProgress: 'plugin:progress',
  ReplacementsGet: 'replacements:get',
  ReplacementsSave: 'replacements:save',
  ReplacementsOpenFile: 'replacements:openFile',
  PublishPrepare: 'publish:prepare',
  PublishPrepareRepublish: 'publish:prepareRepublish',
  PublishExecute: 'publish:execute',
  PublishRollback: 'publish:rollback',
  PublishRepublish: 'publish:republish',
  PublishGetRecords: 'publish:getRecords',
  PublishGetRecord: 'publish:getRecord',
  PublishDeleteRecord: 'publish:deleteRecord',
  PublishProgress: 'publish:progress',
  OperationLog: 'operation:log',
  ProxyGetStatus: 'proxy:getStatus',
  ProxySaveSettings: 'proxy:saveSettings',
  ProxyStart: 'proxy:start',
  ProxyStop: 'proxy:stop',
  ProxyApplyArtifact: 'proxy:applyArtifact',
  ProxyApplyReplacements: 'proxy:applyReplacements',
  ProxyOpenSite: 'proxy:openSite',
  ProxyOpenRoot: 'proxy:openRoot'
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
